---
abstract: 'Process Activity Display Module'
author:
  - 'Phil Pollard <bennie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.96, CPAN::Meta::Converter version 2.120630'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Activity
no_index:
  directory:
    - t
    - inc
    - t
provides:
  Term::Activity:
    file: lib/Term/Activity.pm
    version: 1.20
requires:
  Term::Size: 0
  Test::More: 0
  Test::Simple: 0
  perl: 5.006000
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Term-Activity
  repository: git://github.com/bennie/perl-Term-Activity.git
version: 1.20
